"""Performance review generation logic."""

import os
from datetime import datetime
from pathlib import Path

from config import config
from logging_config import get_logger
from llm import LocalLLM
from database import MongoDatabase
from encryption import encrypt_document
from .prompts import SYSTEM_PROMPT, format_employee_prompt

logger = get_logger(__name__)


class ReviewGenerator:
    """Generates performance review drafts using local LLM."""

    def __init__(self, llm: LocalLLM, db: MongoDatabase):
        self.llm = llm
        self.db = db
        self._ensure_output_dir()

    def _ensure_output_dir(self) -> None:
        """Create output directory if it doesn't exist."""
        Path(config.OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

    def _generate_filename(self, employee_name: str) -> str:
        """
        Generate output filename for a review.

        Args:
            employee_name: Name of the employee.

        Returns:
            Filename with format review_{name}_{date}.md
        """
        safe_name = employee_name.lower().replace(" ", "_")
        date_str = datetime.now().strftime("%Y%m%d")
        return f"review_{safe_name}_{date_str}.md"

    def _format_review_document(self, employee: dict, content: str) -> str:
        """
        Format the complete review document with header and footer.

        Args:
            employee: Employee data.
            content: Generated review content.

        Returns:
            Complete markdown document.
        """
        header = f"""# Performance Review - DRAFT

**Employee:** {employee.get("name", "Unknown")}
**Role:** {employee.get("role", "Unknown")}
**Department:** {employee.get("department", "Unknown")}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** DRAFT - Requires HR Review

---

"""

        footer = """

---

## Important Notice

This performance review is a **DRAFT** generated by an automated system.
It requires thorough review and approval by HR and the employee's direct manager
before being shared with the employee or used for any official purposes.

**This document should not be considered final until approved by HR.**
"""

        return header + content + footer

    def generate_single(self, employee_name: str) -> str:
        """
        Generate a review for a single employee.

        Args:
            employee_name: Name of the employee.

        Returns:
            Path to the generated review file.

        Raises:
            ValueError: If employee not found.
        """
        employee = self.db.get_employee(employee_name)
        if not employee:
            raise ValueError(f"Employee not found: {employee_name}")

        logger.info(f"Generating review for employee")

        prompt = format_employee_prompt(employee)
        content = self.llm.chat(
            system_prompt=SYSTEM_PROMPT,
            user_message=prompt,
            temperature=0.3,
        )

        document = self._format_review_document(employee, content)

        filename = self._generate_filename(employee["name"])
        filepath = os.path.join(config.OUTPUT_DIR, filename)

        # Encrypt sensitive employee data before saving
        encrypted_path = encrypt_document(document, filepath)

        logger.info("Review saved (encrypted)")
        return encrypted_path

    def generate_all(self) -> list[str]:
        """
        Generate reviews for all employees.

        Returns:
            List of paths to generated review files.
        """
        employees = self.db.get_all_employees()

        if not employees:
            logger.warning("No employees found in database.")
            return []

        logger.info(f"Generating reviews for {len(employees)} employees")
        generated_files = []

        for i, employee in enumerate(employees, 1):
            name = employee.get("name", "Unknown")
            logger.info(f"Processing employee {i}/{len(employees)}")

            try:
                filepath = self.generate_single(name)
                generated_files.append(filepath)
            except Exception as e:
                logger.error(f"Error generating review: {e}")

        logger.info(f"Completed! Generated {len(generated_files)} reviews.")
        return generated_files

    def list_employees(self) -> list[str]:
        """
        List all employee names.

        Returns:
            List of employee names.
        """
        return self.db.list_employee_names()
