"""API routes for document generation using LLM."""

import os
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from config import config
from logging_config import get_logger
from database import MongoDatabase
from llm import LocalLLM
from generator.prompts import SYSTEM_PROMPT, format_employee_prompt
from generator.onboarding_prompts import (
    ONBOARDING_SYSTEM_PROMPT,
    format_onboarding_prompt,
)
from .models import OnboardingRequest

logger = get_logger(__name__)

router = APIRouter(prefix="/generate", tags=["generation"])

# Shared instances (initialized on startup)
llm: Optional[LocalLLM] = None
db: Optional[MongoDatabase] = None


class ReviewResponse(BaseModel):
    """Response model for generated review."""

    success: bool
    employee_name: str
    file_path: str
    message: str
    generated_at: str


class OnboardingResponse(BaseModel):
    """Response model for generated onboarding plan."""

    success: bool
    employee_name: str
    file_path: str
    message: str
    generated_at: str


class GenerationError(BaseModel):
    """Error response model."""

    success: bool = False
    error: str
    detail: Optional[str] = None


def init_services(llm_instance: LocalLLM, db_instance: MongoDatabase) -> None:
    """
    Initialize shared service instances.

    Args:
        llm_instance: Loaded LLM instance.
        db_instance: Connected database instance.
    """
    global llm, db
    llm = llm_instance
    db = db_instance
    logger.info("Generation services initialized")


def _generate_review_content(employee: dict) -> str:
    """Generate review content using LLM."""
    prompt = format_employee_prompt(employee)
    return llm.chat(
        system_prompt=SYSTEM_PROMPT,
        user_message=prompt,
        temperature=0.3,
        max_tokens=2048,
    )


def _generate_onboarding_content(data: dict) -> str:
    """Generate onboarding content using LLM."""
    prompt = format_onboarding_prompt(data)
    return llm.chat(
        system_prompt=ONBOARDING_SYSTEM_PROMPT,
        user_message=prompt,
        temperature=0.3,
        max_tokens=2048,
    )


def _format_review_document(employee: dict, content: str) -> str:
    """Format the complete review document."""
    header = f"""# Performance Review - DRAFT

**Employee:** {employee.get("name", "Unknown")}
**Role:** {employee.get("role", "Unknown")}
**Department:** {employee.get("department", "Unknown")}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** DRAFT - Requires HR Review

---

"""
    footer = """

---

## Important Notice

This performance review is a **DRAFT** generated by an automated system.
It requires thorough review and approval by HR and the employee's direct manager
before being shared with the employee or used for any official purposes.

**This document should not be considered final until approved by HR.**
"""
    return header + content + footer


def _format_onboarding_document(data: dict, content: str) -> str:
    """Format the complete onboarding document."""
    header = f"""# Onboarding Plan

**New Hire:** {data.get("employee_name", "Unknown")}
**Role:** {data.get("role", "Unknown")}
**Department:** {data.get("department", "Unknown")}
**Start Date:** {data.get("start_date", "TBD")}
**Manager:** {data.get("manager_name", "Unknown")}
**Buddy:** {data.get("buddy_name", "Not assigned")}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

"""
    footer = """

---

*This onboarding plan was auto-generated. Please review and customize as needed.*
"""
    return header + content + footer


def _save_document(content: str, filename: str) -> str:
    """Save document to output directory."""
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    filepath = os.path.join(config.OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


@router.post(
    "/review/{employee_name}",
    response_model=ReviewResponse,
    responses={
        404: {"model": GenerationError, "description": "Employee not found"},
        500: {"model": GenerationError, "description": "Generation failed"},
    },
    summary="Generate performance review",
    description="Generate a performance review for a specific employee using the local LLM.",
)
def generate_review(employee_name: str):
    """Generate a performance review for an employee."""
    logger.info(f"Review generation requested for: {employee_name}")

    # Check if services are initialized
    if not llm or not db:
        logger.error("Services not initialized")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Generation services not available",
        )

    # Fetch employee
    logger.debug(f"Fetching employee data: {employee_name}")
    employee = db.get_employee(employee_name)

    if not employee:
        logger.warning(f"Employee not found: {employee_name}")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Employee '{employee_name}' not found",
        )

    try:
        # Generate review
        logger.info(f"Generating review content for: {employee_name}")
        start_time = datetime.now()

        content = _generate_review_content(employee)
        document = _format_review_document(employee, content)

        # Save to file
        safe_name = employee_name.lower().replace(" ", "_")
        date_str = datetime.now().strftime("%Y%m%d")
        filename = f"review_{safe_name}_{date_str}.md"
        filepath = _save_document(document, filename)

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(f"Review generated successfully for {employee_name} in {elapsed:.2f}s")

        return ReviewResponse(
            success=True,
            employee_name=employee_name,
            file_path=filepath,
            message=f"Performance review generated successfully in {elapsed:.2f}s",
            generated_at=datetime.now().isoformat(),
        )

    except Exception as e:
        logger.error(f"Failed to generate review for {employee_name}: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate review: {str(e)}",
        )


@router.post(
    "/onboarding",
    response_model=OnboardingResponse,
    responses={
        500: {"model": GenerationError, "description": "Generation failed"},
    },
    summary="Generate onboarding plan",
    description="Generate an onboarding plan for a new hire using the local LLM.",
)
def generate_onboarding(request: OnboardingRequest):
    """Generate an onboarding plan for a new hire."""
    logger.info(f"Onboarding generation requested for: {request.employee_name}")

    # Check if services are initialized
    if not llm:
        logger.error("LLM service not initialized")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Generation services not available",
        )

    try:
        # Generate onboarding plan
        logger.info(f"Generating onboarding content for: {request.employee_name}")
        start_time = datetime.now()

        data = request.model_dump()
        content = _generate_onboarding_content(data)
        document = _format_onboarding_document(data, content)

        # Save to file
        safe_name = request.employee_name.lower().replace(" ", "_")
        date_str = datetime.now().strftime("%Y%m%d")
        filename = f"onboarding_{safe_name}_{date_str}.md"
        filepath = _save_document(document, filename)

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(f"Onboarding plan generated for {request.employee_name} in {elapsed:.2f}s")

        return OnboardingResponse(
            success=True,
            employee_name=request.employee_name,
            file_path=filepath,
            message=f"Onboarding plan generated successfully in {elapsed:.2f}s",
            generated_at=datetime.now().isoformat(),
        )

    except Exception as e:
        logger.error(f"Failed to generate onboarding for {request.employee_name}: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate onboarding plan: {str(e)}",
        )


# =============================================================================
# COMMENTED OUT: Generate all reviews endpoint
# Uncomment when needed - be aware this can take a long time with many employees
# =============================================================================
#
# class BatchReviewResponse(BaseModel):
#     """Response model for batch review generation."""
#     success: bool
#     total_employees: int
#     generated: int
#     failed: int
#     results: list[dict]
#     elapsed_seconds: float
#
#
# @router.post(
#     "/reviews/all",
#     response_model=BatchReviewResponse,
#     summary="Generate all reviews",
#     description="Generate performance reviews for all employees. Warning: This can take a long time.",
# )
# def generate_all_reviews():
#     """Generate reviews for all employees in the database."""
#     logger.info("Batch review generation requested")
#
#     if not llm or not db:
#         raise HTTPException(
#             status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
#             detail="Generation services not available",
#         )
#
#     employees = db.get_all_employees()
#     if not employees:
#         return BatchReviewResponse(
#             success=True,
#             total_employees=0,
#             generated=0,
#             failed=0,
#             results=[],
#             elapsed_seconds=0,
#         )
#
#     logger.info(f"Starting batch generation for {len(employees)} employees")
#     start_time = datetime.now()
#     results = []
#     generated = 0
#     failed = 0
#
#     for employee in employees:
#         name = employee.get("name", "Unknown")
#         try:
#             logger.info(f"Generating review for: {name}")
#             content = _generate_review_content(employee)
#             document = _format_review_document(employee, content)
#
#             safe_name = name.lower().replace(" ", "_")
#             date_str = datetime.now().strftime("%Y%m%d")
#             filename = f"review_{safe_name}_{date_str}.md"
#             filepath = _save_document(document, filename)
#
#             results.append({"name": name, "success": True, "file": filepath})
#             generated += 1
#             logger.info(f"Review generated for: {name}")
#
#         except Exception as e:
#             logger.error(f"Failed to generate review for {name}: {str(e)}")
#             results.append({"name": name, "success": False, "error": str(e)})
#             failed += 1
#
#     elapsed = (datetime.now() - start_time).total_seconds()
#     logger.info(f"Batch generation complete: {generated} success, {failed} failed, {elapsed:.2f}s")
#
#     return BatchReviewResponse(
#         success=failed == 0,
#         total_employees=len(employees),
#         generated=generated,
#         failed=failed,
#         results=results,
#         elapsed_seconds=elapsed,
#     )
